### ISSUE TITLE
Hot bronze chisel never cools down

### ISSUE THREAD

**Issue by Szunti** [UncleGus/OneLifeData7#2]
My target wasn't the chisel, but the flat rock broke and only the hot chisel remained. I can't do anything with it.

**Comment by Szunti** [comment]
I think fb39186ca506a15becec523562812815f120e8ce solves it, I just need to wait until server gets upgraded.

**Comment by UncleGus** [comment]
Completely revamped copper and bronze, so this is obsolete now.
