### ISSUE TITLE
Flat rocks break too easily

### ISSUE THREAD

**Issue by Szunti** [UncleGus/OneLifeData7#4]
I broke 4 or 5 before I could make a blade blank. Add that you can't even get the tin back(#3) and it's really painful to make bronze tools.

**Comment by UncleGus** [comment]
Copper and bronze are getting reworked as casting metals instead of forging, and I'm in the middle of the updates, so I can't fix these issues right now. I'm hoping to have the update out in the next couple of days.

**Comment by UncleGus** [comment]
In the future I will develop updates in a branch so that I can still fix issues like this. Sorry about that.

**Comment by Szunti** [comment]
Sorry, my goal was to help. As you remove all this, my issues are useless and I just waste your time.

**Comment by UncleGus** [comment]
Not a waste of time at all! I haven't had a chance to playtest all my values yet so your feedback is very valuable.

**Comment by UncleGus** [comment]
Completely revamped copper and bronze, so this is obsolete now.
