### ISSUE TITLE
Removing pipe from a kiln with charcoal is a transition dead-end

### ISSUE THREAD

**Issue by Szunti** [UncleGus/OneLifeData7#6]
Probably because @ Adobe Kiln with Charcoal group is missing the Adobe Kiln with Charcoal#pipe removed object.

Does it do anything good to have these distinct tagged objects and put them into a group instead of transitioning into the base object (Adobe Kiln with Charcoal) directly?

**Comment by UncleGus** [comment]
Due to a copy/paste error, the category file had numObjects=2 instead of numObjects=3. This is resolved now, thank you.
